package repl

import (
    "reflect"
    "syscall"
)

func addArchSyscallFuncs(funcs map[string] reflect.Value) {
	funcs["StringSlicePtr"] = reflect.ValueOf(syscall.StringSlicePtr)
	funcs["SlicePtrFromStrings"] = reflect.ValueOf(syscall.SlicePtrFromStrings)
	funcs["ForkExec"] = reflect.ValueOf(syscall.ForkExec)
	funcs["CmsgLen"] = reflect.ValueOf(syscall.CmsgLen)
	funcs["CmsgSpace"] = reflect.ValueOf(syscall.CmsgSpace)
	funcs["ParseSocketControlMessage"] = reflect.ValueOf(syscall.ParseSocketControlMessage)
	funcs["UnixRights"] = reflect.ValueOf(syscall.UnixRights)
	funcs["ParseUnixRights"] = reflect.ValueOf(syscall.ParseUnixRights)
	funcs["Futimes"] = reflect.ValueOf(syscall.Futimes)
	funcs["Setgroups"] = reflect.ValueOf(syscall.Setgroups)
	funcs["Wait4"] = reflect.ValueOf(syscall.Wait4)
	funcs["Mkfifo"] = reflect.ValueOf(syscall.Mkfifo)
	funcs["GetsockoptInet4Addr"] = reflect.ValueOf(syscall.GetsockoptInet4Addr)
	funcs["GetsockoptIPMreq"] = reflect.ValueOf(syscall.GetsockoptIPMreq)
	funcs["GetsockoptIPv6Mreq"] = reflect.ValueOf(syscall.GetsockoptIPv6Mreq)
	funcs["GetsockoptIPv6MTUInfo"] = reflect.ValueOf(syscall.GetsockoptIPv6MTUInfo)
	funcs["GetsockoptICMPv6Filter"] = reflect.ValueOf(syscall.GetsockoptICMPv6Filter)
	funcs["Recvmsg"] = reflect.ValueOf(syscall.Recvmsg)
	funcs["Sendmsg"] = reflect.ValueOf(syscall.Sendmsg)
	funcs["PtraceAttach"] = reflect.ValueOf(syscall.PtraceAttach)
	funcs["PtraceDetach"] = reflect.ValueOf(syscall.PtraceDetach)
	funcs["ReadDirent"] = reflect.ValueOf(syscall.ReadDirent)
	funcs["ParseDirent"] = reflect.ValueOf(syscall.ParseDirent)
	funcs["Mmap"] = reflect.ValueOf(syscall.Mmap)
	funcs["Munmap"] = reflect.ValueOf(syscall.Munmap)
	funcs["TimevalToNsec"] = reflect.ValueOf(syscall.TimevalToNsec)
	funcs["Getrlimit"] = reflect.ValueOf(syscall.Getrlimit)
	funcs["Setrlimit"] = reflect.ValueOf(syscall.Setrlimit)
	funcs["Fstatfs"] = reflect.ValueOf(syscall.Fstatfs)
	funcs["Statfs"] = reflect.ValueOf(syscall.Statfs)
	funcs["RawSyscall"] = reflect.ValueOf(syscall.RawSyscall)
	funcs["RawSyscall6"] = reflect.ValueOf(syscall.RawSyscall6)
	funcs["SetsockoptByte"] = reflect.ValueOf(syscall.SetsockoptByte)
	funcs["SetsockoptICMPv6Filter"] = reflect.ValueOf(syscall.SetsockoptICMPv6Filter)
	funcs["SetsockoptString"] = reflect.ValueOf(syscall.SetsockoptString)
	funcs["Socketpair"] = reflect.ValueOf(syscall.Socketpair)
	funcs["Sendfile"] = reflect.ValueOf(syscall.Sendfile)
	funcs["Access"] = reflect.ValueOf(syscall.Access)
	funcs["Chroot"] = reflect.ValueOf(syscall.Chroot)
	funcs["Dup"] = reflect.ValueOf(syscall.Dup)
	funcs["Dup2"] = reflect.ValueOf(syscall.Dup2)
	funcs["Flock"] = reflect.ValueOf(syscall.Flock)
	funcs["Getpgid"] = reflect.ValueOf(syscall.Getpgid)
	funcs["Getpgrp"] = reflect.ValueOf(syscall.Getpgrp)
	funcs["Getpriority"] = reflect.ValueOf(syscall.Getpriority)
	funcs["Getrusage"] = reflect.ValueOf(syscall.Getrusage)
	funcs["Kill"] = reflect.ValueOf(syscall.Kill)
	funcs["Mknod"] = reflect.ValueOf(syscall.Mknod)
	funcs["Setpgid"] = reflect.ValueOf(syscall.Setpgid)
	funcs["Setsid"] = reflect.ValueOf(syscall.Setsid)
	funcs["Settimeofday"] = reflect.ValueOf(syscall.Settimeofday)
	funcs["Setuid"] = reflect.ValueOf(syscall.Setuid)
	funcs["Setpriority"] = reflect.ValueOf(syscall.Setpriority)
	funcs["Sync"] = reflect.ValueOf(syscall.Sync)
	funcs["Umask"] = reflect.ValueOf(syscall.Umask)
	funcs["Unmount"] = reflect.ValueOf(syscall.Unmount)
	funcs["Fstat"] = reflect.ValueOf(syscall.Fstat)
	funcs["Lstat"] = reflect.ValueOf(syscall.Lstat)
	funcs["Pread"] = reflect.ValueOf(syscall.Pread)
	funcs["Pwrite"] = reflect.ValueOf(syscall.Pwrite)
	funcs["Setgid"] = reflect.ValueOf(syscall.Setgid)
	funcs["Setregid"] = reflect.ValueOf(syscall.Setregid)
	funcs["Setreuid"] = reflect.ValueOf(syscall.Setreuid)
	funcs["Stat"] = reflect.ValueOf(syscall.Stat)
	funcs["Truncate"] = reflect.ValueOf(syscall.Truncate)
	funcs["Select"] = reflect.ValueOf(syscall.Select)
	funcs["Gettimeofday"] = reflect.ValueOf(syscall.Gettimeofday)
}

func addArchSyscallTypes(types map[string] reflect.Type) {
	types["Credential"] = reflect.TypeOf(*new(syscall.Credential))
	types["SocketControlMessage"] = reflect.TypeOf(*new(syscall.SocketControlMessage))
	types["Rlimit"] = reflect.TypeOf(*new(syscall.Rlimit))
	types["Stat_t"] = reflect.TypeOf(*new(syscall.Stat_t))
	types["Statfs_t"] = reflect.TypeOf(*new(syscall.Statfs_t))
	types["Dirent"] = reflect.TypeOf(*new(syscall.Dirent))
	types["Fsid"] = reflect.TypeOf(*new(syscall.Fsid))
	types["RawSockaddrUnix"] = reflect.TypeOf(*new(syscall.RawSockaddrUnix))
	types["Iovec"] = reflect.TypeOf(*new(syscall.Iovec))
	types["Msghdr"] = reflect.TypeOf(*new(syscall.Msghdr))
	types["Cmsghdr"] = reflect.TypeOf(*new(syscall.Cmsghdr))
	types["Inet4Pktinfo"] = reflect.TypeOf(*new(syscall.Inet4Pktinfo))
	types["Inet6Pktinfo"] = reflect.TypeOf(*new(syscall.Inet6Pktinfo))
	types["IPv6MTUInfo"] = reflect.TypeOf(*new(syscall.IPv6MTUInfo))
	types["ICMPv6Filter"] = reflect.TypeOf(*new(syscall.ICMPv6Filter))
	types["FdSet"] = reflect.TypeOf(*new(syscall.FdSet))
	types["Termios"] = reflect.TypeOf(*new(syscall.Termios))
}
